import './helpers/colors/getLegibleTextColor.test.js';
import './helpers/colors/getLuminance.test';
import './helpers/colors/hexToRgb.test.js';
import './helpers/colors/parseColor.test.js';
import './server/crudMethods.test.js';
import './server/getCollection.test.js';
import './server/permissions.test.js';
import './server/questionnaireInterval.test.js';
import './server/validation.test.js';
