import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

type LocaleName = 'en' | 'de' | 'fr';
type FlatLocale = Record<string, string>;

const LOCALES = ['en', 'de', 'fr'] as const satisfies readonly LocaleName[];

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const localesDir = resolve(root, 'imports/i18n/locales');
const outPath = resolve(root, 'imports/i18n/translations.ts');

function loadLocale(name: LocaleName): unknown {
  return JSON.parse(readFileSync(resolve(localesDir, `${name}.json`), 'utf8'));
}

function flatten(input: unknown, prefix = '', out: FlatLocale = {}): FlatLocale {
  if (input === null || typeof input !== 'object' || Array.isArray(input)) {
    throw new Error(`Expected object at "${prefix}", got ${input === null ? 'null' : Array.isArray(input) ? 'array' : typeof input}`);
  }
  for (const [key, value] of Object.entries(input as Record<string, unknown>)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (typeof value === 'string') {
      out[path] = value;
    } else if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
      flatten(value, path, out);
    } else {
      throw new Error(`Unsupported value at "${path}": ${typeof value}`);
    }
  }
  return out;
}

function diff(a: FlatLocale, b: FlatLocale): { onlyInA: string[]; onlyInB: string[] } {
  const aKeys = new Set(Object.keys(a));
  const bKeys = new Set(Object.keys(b));
  return {
    onlyInA: [...aKeys].filter(k => !bKeys.has(k)).sort(),
    onlyInB: [...bKeys].filter(k => !aKeys.has(k)).sort(),
  };
}

const flat: Record<LocaleName, FlatLocale> = {
  en: flatten(loadLocale('en')),
  de: flatten(loadLocale('de')),
  fr: flatten(loadLocale('fr')),
};

let hasMismatch = false;
for (const name of LOCALES.slice(1) as LocaleName[]) {
  const { onlyInA: missingHere, onlyInB: extraHere } = diff(flat.en, flat[name]);
  if (missingHere.length || extraHere.length) {
    hasMismatch = true;
    console.error(`\nLocale "${name}" diverges from "en":`);
    if (missingHere.length) console.error(`  missing in ${name}:`, missingHere);
    if (extraHere.length) console.error(`  extra in ${name}:  `, extraHere);
  }
}
if (hasMismatch) {
  console.error('\nFix the JSON files and re-run.');
  process.exit(1);
}

const keys = Object.keys(flat.en).sort();

const lines: string[] = [
  '// AUTO-GENERATED by scripts/i18n-merge.ts — do not edit by hand.',
  '// Re-run the codemod (npm run i18n:merge) to regenerate from imports/i18n/locales/*.json.',
  '',
  "export type Locale = 'en' | 'de' | 'fr';",
  '',
  'export type TranslationSet = Record<string, Record<Locale, string>>;',
  '',
  'export const translations = {',
];

for (const key of keys) {
  const row = LOCALES.map(loc => `${loc}: ${JSON.stringify(flat[loc][key])}`).join(', ');
  lines.push(`  ${JSON.stringify(key)}: { ${row} },`);
}

lines.push('} as const satisfies TranslationSet;');
lines.push('');

writeFileSync(outPath, lines.join('\n'), 'utf8');

console.log(`Wrote ${keys.length} entries to ${outPath}`);
